module.exports = {
  ALL_MATCHES_RECEIVED: "ALL_MATCHES_RECEIVED",
  ALL_HEROES_RECEIVED: "ALL_HEROES_RECEIVED",
  ALL_ITEMS_RECEIVED: "ALL_ITEMS_RECEIVED",
  ALL_ABILITIES_RECEIVED: "ALL_ABILITIES_RECEIVED",

  SET_GAME_FILTER: "SET_MODE_FILTER",
  SET_HERO_FILTER: "SET_HERO_FILTER",
  RESET_ALL_FILTERS: "RESET_ALL_FILTERS"
};
