module.exports = {
  0: "All",
  1: "All Pick",
  2: "Captain's Mode",
  3: "Random Draft",
  4: "Single Draft",
  5: "All Random",
  // 6: "Intro",
  // 7: "Diretide",
  // 8: "Reverse Captain's Mode",
  // 9: "The Greeviling",
  // 10: "Tutorial",
  // 11: "Mid Only",
  // 12: "Least Played",
  // 13: "Limited Hero Pool",
  // 14: "Compendium Matchmaking",
  // 15: "Custom",
  16: "Captain's Draft",
  // 17: "Balanced Draft",
  // 18: "Ability Draft",
  // 19: "Event",
  // 20: "All Random Death Match",
  21: "1v1 Solo Mid",
  22: "Ranked All Pick"
};
