var GfycatNames = {
  "Abaddon": "BrownSelfassuredAbyssiniancat",
  "Alchemist": "GracefulWearyFruitfly",
  "Ancient Apparition": "FarawayInfatuatedEyas",
  "Anti-Mage": "PettyZigzagCopperhead",
  "Arc Warden": "EnragedWarmheartedAsiaticlesserfreshwaterclam",
  "Axe": "PaltryAltruisticKiwi",
  "Bane": "PossibleTintedDunnart",
  "Batrider": "JollyGlisteningGander",
  "Beastmaster": "DishonestBarrenGreendarnerdragonfly",
  "Bloodseeker": "EverlastingPoshKangaroo",
  "Bounty Hunter": "PerkyImmediateBlueandgoldmackaw",
  "Brewmaster": "MaleSmoothHeron",
  "Bristleback": "PhysicalSparseBaldeagle",
  "Broodmother": "TinySnarlingDorado",
  "Centaur Warrunner": "PeacefulShockedAruanas",
  "Chaos Knight": "LimpingOffensiveDamselfly",
  "Chen": "JovialPracticalBluebreastedkookaburra",
  "Clinkz": "ClumsyInnocentFunnelweaverspider",
  "Crystal Maiden": "PiercingJitteryAntbear",
  "Dark Seer": "SneakyBoilingAsianlion",
  "Dazzle": "EasyOddballIggypops",
  "Death Prophet": "AliveBlaringCoyote",
  "Disruptor": "SomeTenseGartersnake",
  "Doom": "InfantileDimwittedAmericanratsnake",
  "Dragon Knight": "BountifulEuphoricKiskadee",
  "Drow Ranger": "ConcreteWelcomeBadger",
  "Earth Spirit": "SlimTotalAlligatorsnappingturtle",
  "Earthshaker": "CheapDirtyAdmiralbutterfly",
  "Elder Titan": "ThickTornDorado",
  "Ember Spirit": "ExhaustedInsecureAlaskanhusky",
  "Enchantress": "AdolescentObedientHorse",
  "Enigma": "ElderlyEagerArachnid",
  "Faceless Void": "MajorColorlessBunny",
  "Nature's Prophet": "FreshGoldenDobermanpinscher",
  "Gyrocopter": "CourageousFreshIslandwhistler",
  "Huskar": "IckyImpressiveArmedcrab",
  "Invoker": "KnobbyReasonableAllensbigearedbat",
  "Jakiro": "DearestWeightyFeline",
  "Juggernaut": "OptimalLeanAssassinbug",
  "Keeper of the Light": "ShabbyTornGourami",
  "Kunkka": "PrestigiousLinearFallowdeer",
  "Legion Commander": "AccuratePlushAfricanfisheagle",
  "Leshrac": "PracticalShimmeringAstarte",
  "Lich": "TallPowerlessCardinal",
  "Lifestealer": "SizzlingGroundedHummingbird",
  "Lina": "YellowBriefGavial",
  "Lion": "GrayKindheartedKawala",
  "Lone Druid": "DenseAromaticKagu",
  "Luna": "MadeupDenseKusimanse",
  "Lycan": "VainBiodegradableGull",
  "Magnus": "ZealousMilkyElephant",
  "Medusa": "FirmOptimisticAfricanpiedkingfisher",
  "Meepo": "GoodEnlightenedHydra",
  "Mirana": "LargeBackElkhound",
  "Morphling": "ColorfulDaringCapeghostfrog",
  "Naga Siren": "MelodicElaborateAplomadofalcon",
  "Necrophos": "LeadingEvilFritillarybutterfly",
  "Shadow Fiend": "NimbleUnnaturalDonkey",
  "Night Stalker": "FinishedYearlyChital",
  "Nyx Assassin": "KeenImpartialAlaskankleekai",
  "Outworld Devourer": "WanBothEider",
  "Ogre Magi": "DelayedClosedBoto",
  "Omniknight": "WelltodoFlakyBuck",
  "Oracle": "PalatableWeightyBilby",
  "Phantom Assassin": "ConcreteClassicFrigatebird",
  "Phantom Lancer": "PoliticalRelievedDogwoodtwigborer",
  "Phoenix": "RawEmotionalHamster",
  "Puck": "PoliteAdventurousFeline",
  "Pudge": "SomeAcademicCooter",
  "Pugna": "QuerulousFalseDeermouse",
  "Queen of Pain": "RingedParallelElkhound",
  "Clockwerk": "FineCommonDipper",
  "Razor": "SomeMindlessAustraliansilkyterrier",
  "Riki": "ImperfectForcefulKangaroo",
  "Rubick": "SeparateConcernedFreshwatereel",
  "Sand King": "GlaringConsciousGreendarnerdragonfly",
  "Shadow Demon": "TallCookedFairyfly",
  "Shadow Shaman": "EagerUniqueEthiopianwolf",
  "Timbersaw": "SingleRingedBarasingha",
  "Silencer": "EnergeticAgonizingAlaskankleekai",
  "Wraith King": "ContentFrigidDrake",
  "Skywrath Mage": "MammothUnfoldedHylaeosaurus",
  "Slardar": "LeafyLimpAfricanmolesnake",
  "Slark": "IdealisticUnfoldedGoa",
  "Sniper": "GrippingSparklingHerculesbeetle",
  "Spectre": "AdolescentInexperiencedHarpseal",
  "Spirit Breaker": "ShinyUnequaledGermanpinscher",
  "Storm Spirit": "ThinAppropriateArcticseal",
  "Sven": "TenseQualifiedAmurminnow",
  "Techies": "FelineCorruptHaddock",
  "Templar Assassin": "ScalyHotArcticwolf",
  "Terrorblade": "GrippingBareIberianchiffchaff",
  "Tidehunter": "GivingUnrulyIlsamochadegu",
  "Tinker": "FriendlyMilkyFlee",
  "Tiny": "SillyIncomparableJay",
  "Treant Protector": "WelloffSafeGrasshopper",
  "Troll Warlord": "SoftAncientGerbil",
  "Tusk": "LoathsomeFarawayAmericanratsnake",
  "Undying": "ScentedQuaintDegus",
  "Ursa": "BitterHeartfeltDorking",
  "Vengeful Spirit": "RedImpoliteCockerspaniel",
  "Venomancer": "MaleWhiteFluke",
  "Viper": "MarriedJoyousFish",
  "Visage": "SpecificTemptingChick",
  "Warlock": "AfraidFearlessHumpbackwhale",
  "Weaver": "SpottedPositiveAmericanlobster",
  "Windranger": "VillainousSociableCarpenterant",
  "Winter Wyvern": "HighInsignificantAtlanticblackgoby",
  "Io": "DetailedEdibleHuia",
  "Witch Doctor": "DetailedRelievedAnemoneshrimp",
  "Zeus": "PreciousMelodicGuillemot"
};

module.exports = GfycatNames;
