var PrimaryStats = {
  "Abaddon": "Strength",
  "Alchemist": "Strength",
  "Ancient Apparition": "Intelligence",
  "Anti-Mage": "Agility",
  "Arc Warden": "Agility",
  "Axe": "Strength",
  "Bane": "Intelligence",
  "Batrider": "Intelligence",
  "Beastmaster": "Strength",
  "Bloodseeker": "Agility",
  "Bounty Hunter": "Agility",
  "Brewmaster": "Strength",
  "Bristleback": "Strength",
  "Broodmother": "Agility",
  "Centaur Warrunner": "Strength",
  "Chaos Knight": "Strength",
  "Chen": "Intelligence",
  "Clinkz": "Agility",
  "Crystal Maiden": "Intelligence",
  "Dark Seer": "Intelligence",
  "Dazzle": "Intelligence",
  "Death Prophet": "Intelligence",
  "Disruptor": "Intelligence",
  "Doom": "Strength",
  "Dragon Knight": "Strength",
  "Drow Ranger": "Agility",
  "Earth Spirit": "Strength",
  "Earthshaker": "Strength",
  "Elder Titan": "Strength",
  "Ember Spirit": "Agility",
  "Enchantress": "Intelligence",
  "Enigma": "Intelligence",
  "Faceless Void": "Agility",
  "Nature's Prophet": "Intelligence",
  "Gyrocopter": "Agility",
  "Huskar": "Strength",
  "Invoker": "Intelligence",
  "Jakiro": "Intelligence",
  "Juggernaut": "Agility",
  "Keeper of the Light": "Intelligence",
  "Kunkka": "Strength",
  "Legion Commander": "Strength",
  "Leshrac": "Intelligence",
  "Lich": "Intelligence",
  "Lifestealer": "Strength",
  "Lina": "Intelligence",
  "Lion": "Intelligence",
  "Lone Druid": "Agility",
  "Luna": "Agility",
  "Lycan": "Strength",
  "Magnus": "Strength",
  "Medusa": "Agility",
  "Meepo": "Agility",
  "Mirana": "Agility",
  "Morphling": "Agility",
  "Naga Siren": "Agility",
  "Necrophos": "Intelligence",
  "Shadow Fiend": "Agility",
  "Night Stalker": "Strength",
  "Nyx Assassin": "Agility",
  "Outworld Devourer": "Intelligence",
  "Ogre Magi": "Intelligence",
  "Omniknight": "Strength",
  "Oracle": "Intelligence",
  "Phantom Assassin": "Agility",
  "Phantom Lancer": "Agility",
  "Phoenix": "Strength",
  "Puck": "Intelligence",
  "Pudge": "Strength",
  "Pugna": "Intelligence",
  "Queen of Pain": "Intelligence",
  "Clockwerk": "Strength",
  "Razor": "Agility",
  "Riki": "Agility",
  "Rubick": "Intelligence",
  "Sand King": "Strength",
  "Shadow Demon": "Intelligence",
  "Shadow Shaman": "Intelligence",
  "Timbersaw": "Strength",
  "Silencer": "Intelligence",
  "Wraith King": "Strength",
  "Skywrath Mage": "Intelligence",
  "Slardar": "Strength",
  "Slark": "Agility",
  "Sniper": "Agility",
  "Spectre": "Agility",
  "Spirit Breaker": "Strength",
  "Storm Spirit": "Intelligence",
  "Sven": "Strength",
  "Techies": "Intelligence",
  "Templar Assassin": "Agility",
  "Terrorblade": "Agility",
  "Tidehunter": "Strength",
  "Tinker": "Intelligence",
  "Tiny": "Strength",
  "Treant Protector": "Strength",
  "Troll Warlord": "Agility",
  "Tusk": "Strength",
  "Undying": "Strength",
  "Ursa": "Agility",
  "Vengeful Spirit": "Agility",
  "Venomancer": "Agility",
  "Viper": "Agility",
  "Visage": "Intelligence",
  "Warlock": "Intelligence",
  "Weaver": "Agility",
  "Windranger": "Intelligence",
  "Winter Wyvern": "Intelligence",
  "Io": "Intelligence",
  "Witch Doctor": "Intelligence",
  "Zeus": "Intelligence"
};

module.exports = PrimaryStats;
